# Use an official Node.js runtime as a parent image
FROM node:17 AS node

# Set the working directory
WORKDIR /var/www

# Copy package.json and package-lock.json (if exists) to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Expose the application port
EXPOSE 3000

# Start the Node.js app (if needed)
CMD ["npm"]
